### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nicolasmaia** [MycroftAI/MycroftCore-Android#14]
There seems to be none.

**Comment by krisgesling** [comment]
Hi there, thanks for flagging the lack of a license. 

This project is a community driven initiative so I think it's up to the existing community contributors (@paulscott56 @skraynick and @Stypox ) what license they'd like to use. 

Our standard license is Apache 2.0, so for the sake of having a starting proposal, would everyone be comfortable with that? Otherwise please propose an alternative.

**Comment by skraynick** [comment]
Thanks for flagging. Strangely I thought we had a license. I think a
standard OS license should do it. MIT. What do the other projects in.
Mycroft use? Off-grid at the moment so my response time is slow.

**Comment by Stypox** [comment]
IANAL, but I think MIT would be a good starting point, because as far as I know it allows to later change the license to a stricter one without much hassle.

**Comment by krisgesling** [comment]
MIT seems like a good choice. 

Almost everything in Mycroft is Apache 2.0, except for our backend Selene which is AGPL 3.0. 

Community Skills can be any Open Source Initiative approved license.

**Comment by strugee** [comment]
The GNU project recommends Apache 2.0 instead of the MIT/Expat license because it offers better protection from patent-related issues: see https://www.gnu.org/licenses/license-list.html#Expat. Of course it's entirely up to the folks actually writing code for this project - just figured I'd raise it as something to consider :-)

**Comment by paulscott56** [comment]
As the person that started this project, I would prefer the most open possible. Apache 2.0 seems a good choice

**Comment by skraynick** [comment]
I am fine with either. Which ever the consensus wants seems like the way to go.. :)

**Comment by krisgesling** [comment]
Great, I'll add an Apache 2.0 license unless anyone objects in the next few days.

**Comment by krisgesling** [comment]
Apache 2.0 applied and updated the badge on the README. 

Thanks all
